os:
  - linux
language: node_js
node_js:
  - "6.10.0"
addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - $HOME/.m2
    - node_modules
before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - export PATH=$JAVA_HOME/bin:$PATH
  - java -version
  - npm install -g @angular/cli@latest
install:
  - cd "$TRAVIS_BUILD_DIR"/quickstart
  - ng new web
  - mvn -Pdb,metadata,gen generate-sources
script:
  - mvn test
  - cd web
  - ng test
