os:
  - linux
language: node_js
node_js:
  - "6.10.0"
addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - $HOME/.m2
    - node_modules
before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - export PATH=$JAVA_HOME/bin:$PATH
  - java -version
  - npm install -g @angular/cli@latest
  - export DISPLAY=:99.0
  - export CHROME_BIN=chromium-browser
  - mkdir ~/.config
  - echo "--no-sandbox" > ~/.config/chromium-flags.conf
  - export KARMA_SINGLE_RUN=true
  - sh -e /etc/init.d/xvfb start
install:
  - cd "$TRAVIS_BUILD_DIR"/quickstart
  - ng new web
  - rm web/src/main.ts web/src/app/app.module.ts web/src/app/app.component.* web/src/styles.css
  - mvn -Pdb,metadata,gen generate-sources
  - cd web
  - npm install --save @angular/animations
  - npm install --save @angular/material
  - npm install --save primeng
  - npm install --save font-awesome
  - cd ..
script:
  - mvn test
  - cd web
  - ng test
